title: Michael's blog
author: Michael Luo
email: luomichaelcunhao@gmail.com
description: >
  Michael's personal website.

theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax

header_pages:
  - index.md
  - citizenship.md
  - handouts.md
  - diaries.md
