title: Knowing Ant
description: Handouts and private diary PDFs
theme: minima
markdown: kramdown
collections:
  handouts:
    output: true
    permalink: /handouts/:name/
  diaries:
    output: true
    permalink: /diaries/:name/
defaults:
  - scope:
      path: ""
      type: handouts
    values:
      layout: entry
      section: Handouts
  - scope:
      path: ""
      type: diaries
    values:
      layout: entry
      section: Diaries
